### ISSUE TITLE
Google Login fail

### ISSUE THREAD

**Issue by bmbariah** [kakadu-dev/android-sociallogin#1]
Google login fails with error:  W/SocialLogin: 10 - DEVELOPER_ERROR

Steps to recreate:
1. Clone & Build project from github
2. Change default_web_id to my own
3. Run app

Full logs:
`W/SocialLogin: Google sign in failed
    com.google.android.gms.common.api.ApiException: 10: 
        at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(Unknown Source:4)
        at com.google.android.gms.auth.api.signin.GoogleSignIn.getSignedInAccountFromIntent(Unknown Source:8)
        at bz.kakadu.sociallogin.GoogleModule.onActivityResult(GoogleModule.kt:52)
        at bz.kakadu.sociallogin.SocialLogin.onActivityResult(SocialLogin.kt:48)
        at android.app.Activity.dispatchActivityResult(Activity.java:7462)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4392)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4441)`

**Comment by RomanTsarou** [comment]
Go to https://console.cloud.google.com/apis/credentials with your registered app

![credentials](https://user-images.githubusercontent.com/15124891/57286537-18949a80-70be-11e9-84e3-de359d806d8b.jpg)
